"""Fetch client information HTML from Qualer and store in database.

Endpoint: GET /Client/ClientInformation
"""

import json

from utils.auth import QualerAPIFetcher
from tqdm import tqdm


def fetch_and_store(client_ids: list, api: QualerAPIFetcher = None) -> None:
    """
    Fetch and store client information for all clients.

    Fetches the HTML form for each client from the Qualer API and stores
    the raw responses in the datadump table for later parsing.

    Args:
        client_ids: List of client IDs to fetch
        api: Optional QualerAPIFetcher instance. If not provided, creates new context manager.
    """

    def _do_fetch(fetcher):
        for clientid in tqdm(client_ids, desc="Fetching client data", dynamic_ncols=True):
            url = f"https://jgiquality.qualer.com/Client/ClientInformation?clientId={clientid}"
            fetcher.fetch_and_store(url, "ClientInformation")

    if api:
        _do_fetch(api)
    else:
        with QualerAPIFetcher() as api:
            _do_fetch(api)


def main(clients_file: str = "data/clients.json") -> None:
    """
    Load client list from JSON and fetch their information.

    Args:
        clients_file: Path to clients.json file (generated by client_dashboard.clients_read)
    """
    # Load client list from JSON (generated by clients_read)
    with open(clients_file, "r") as f:
        data = json.load(f)

    # Extract client IDs from API response format
    client_list = data.get("data", []) if isinstance(data, dict) else data
    client_ids = [c["Id"] for c in client_list]
    print(f"Loaded {len(client_ids)} clients from {clients_file}")

    fetch_and_store(client_ids)
