"""
Fetch client information HTML from Qualer and store in database.

This script uses the client.client_information endpoint to fetch and store
client HTML forms for later parsing.
"""

from qualer_internal_sdk.endpoints.client.client_information import fetch_and_store
import json


def main(clients_file: str = "data/clients.json") -> None:
    """
    Load client list from JSON and fetch their information.

    Args:
        clients_file: Path to clients.json file (generated by client_dashboard.clients_read)
    """
    import os

    if not os.path.exists(clients_file):
        raise FileNotFoundError(
            f"Clients file not found: {clients_file}\n"
            "Please run the clients_read endpoint first to generate this file."
        )

    # Load client list from JSON (generated by clients_read)
    with open(clients_file, "r") as f:
        data = json.load(f)

    # Extract client IDs from API response format
    # Support both legacy "Data" and newer "data" key casing from the API
    if isinstance(data, dict):
        client_list = data.get("data") or data.get("Data") or []
    else:
        client_list = data
    client_ids = [c["Id"] for c in client_list]
    print(f"Loaded {len(client_ids)} clients from {clients_file}")

    fetch_and_store(client_ids)


if __name__ == "__main__":
    main()
