"""
Fetch client information HTML from Qualer and store in database.

This script reads the client list from data/clients.json (generated by Clients_Read.py),
fetches the HTML form for each client from the Qualer API, and stores the raw responses
in the datadump table for later parsing.
"""

import json
import os
from utils.auth import QualerAPIFetcher
from tqdm import tqdm


def main():
    """Fetch and store client information for all clients."""
    # Check if clients.json exists
    clients_file = "data/clients.json"
    if not os.path.exists(clients_file):
        raise FileNotFoundError(
            f"{clients_file} not found. Please run Clients_Read.py first to generate the client list."
        )

    # Load client list from JSON (generated by Clients_Read.py)
    with open(clients_file, "r") as f:
        data = json.load(f)

    # Extract client IDs from API response format
    client_list = data.get("Data", []) if isinstance(data, dict) else data
    client_ids = [c["Id"] for c in client_list]
    print(f"Loaded {len(client_ids)} clients from data/clients.json")

    with QualerAPIFetcher() as api:

        # Fetch and store HTML for each client
        for client_id in tqdm(client_ids, desc="Fetching client data", dynamic_ncols=True):
            url = f"https://jgiquality.qualer.com/Client/ClientInformation?clientId={client_id}"
            try:
                api.fetch_and_store(url, "ClientInformation")
            except Exception as e:
                # Skip clients with permission errors or other failures
                import traceback

                print(f"\nWarning: Failed to fetch client {client_id}: {e}")
                print(f"Traceback: {traceback.format_exc()}")
                continue


if __name__ == "__main__":
    main()
