"""
Fetch client information HTML from Qualer and store in database.

This script reads the client list from data/clients.json (generated by Clients_Read.py),
fetches the HTML form for each client from the Qualer API, and stores the raw responses
in the datadump table for later parsing.
"""

import json
from utils.auth import QualerAPIFetcher
from tqdm import tqdm


def main():
    """Fetch and store client information for all clients."""
    # Load client list from JSON (generated by Clients_Read.py)
    with open("data/clients.json", "r") as f:
        data = json.load(f)

    # Extract client IDs from API response format
    client_list = data.get("Data", []) if isinstance(data, dict) else data
    client_ids = [c["Id"] for c in client_list]
    print(f"Loaded {len(client_ids)} clients from data/clients.json")

    with QualerAPIFetcher() as api:

        # Fetch and store HTML for each client
        for clientid in tqdm(client_ids, desc="Fetching client data", dynamic_ncols=True):
            url = f"https://jgiquality.qualer.com/Client/ClientInformation?clientId={clientid}"
            api.fetch_and_store(url, "ClientInformation")


if __name__ == "__main__":
    main()
